version: '3.3'

services:
  php:
    container_name: php_restaurant_serivce
    build:
      context: ./php
    restart: always
    volumes:
      - ./src:/home/app/src:Z
    links:
      - mysql
      - redis
    working_dir: /home/app/src

  nginx:
    image: nginx:1.14.2-alpine
    restart: always
    volumes:
      - ./nginx/resolve.conf:/etc/nginx/conf.d/default.conf
      - ./src:/home/app/src
    links:
      - php
    ports:
      - 127.0.0.1:30:80
    working_dir: /home/app/src

  mysql:
    image: mariadb:10.6
    container_name: mysql_restaurant_service
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=restaurant_service
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
    ports:
      - 127.0.0.1:33063:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_PORT=3306
    ports:
      - 31:80
    volumes:
      - /sessions
    links:
      - mysql

  redis:
    image: redis:alpine

volumes:
  composer-cache:
